name: CI/CD Pipeline - Back Ventas

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagen a Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # ¡Ojo aquí! Cambia el nombre de la imagen
          tags: marcelo1993/back-ventas:latest
